# Generated by Django 4.2.5 on 2023-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.TextField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.TextField(max_length=100)),
            ],
        ),
    ]
