# Generated by Django 4.2.5 on 2023-09-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_veiculos', '0002_rename_veiculos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
